---
all:
  hosts:
    10.3.10.11:
    10.3.10.12:
    10.3.10.13:
  children:
    primary:
      hosts:
        #IP
        10.3.10.11:
    secondary:
      hosts:
        #IP
        10.3.10.12:
    member:
      hosts:
        #IP
        10.3.10.13:
...